version: '3'

networks:
  laravel:

services:

  app:
    container_name: ${PREFIX}_app
    image: ${PREFIX}_app
    build: ./fpm
    restart: always
    volumes:
      - ${SOURCE_DIR}:${TARGET_DIR}

  nginx:
    container_name: ${PREFIX}_nginx
    image: ${PREFIX}_nginx
    build: ./nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ${SOURCE_DIR}:${TARGET_DIR}
      - ./nginx/sites:/etc/nginx/conf.d
    links:
      - app
    stdin_open: true
    tty: true

  db:
    image: mariadb:10.4
    container_name: ${PREFIX}_db
    restart: always
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${PREFIX}_phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db

  redis:
    image: redis:latest
    container_name: ${PREFIX}_redis
    working_dir: ${APP_PATH_CONTAINER}
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - ${REDIS_PATH_CONF}:/redis.conf
    command: [ "redis-server", "/redis.conf" ]

#  elasticsearch:
#    image: elasticsearch:7.8.1
#    container_name: ${PREFIX}_elasticsearch
#    volumes:
#      - ./elasticsearch/healthcheck.sh:/bin/healthcheck.sh
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    environment:
#      discovery.type: single-node
#    healthcheck:
#      test: ['CMD', 'bash', '/bin/healthcheck.sh']
#      interval: 10s
#      timeout: 20s
#      retries: 3

#  rabbitmq:
#    image: rabbitmq:3-management-alpine
#    container_name: ${PREFIX}_rabbitmq
#    ports:
#      - "15672:15672"
#      - "5672:5672"
#    volumes:
#      - ${RABBIT_MQ_DATA}:/var/lib/rabbitmq/
#      - ${RABBIT_MQ_LOGS}:/var/log/rabbitmq
#      - ./queues/healthcheck.sh:/bin/healthcheck.sh
#    healthcheck:
#      test: ['CMD', 'bash', '/bin/healthcheck.sh']
#      interval: 5s
#      timeout: 10s
#      retries: 3
